[theme]
primaryColor = "#7c6af7"
backgroundColor = "#f8f7ff"
secondaryBackgroundColor = "#eeedf9"
textColor = "#1e1a3c"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
